import SourceList from '../components/SourceList'
import { useEffect, useState } from 'react'

const H = ({ children }: { children: string }) => <h2 className="display text-3xl font-medium mt-14 mb-4 pt-8 border-t border-hairline/70">{children}</h2>
const P = ({ children }: { children: React.ReactNode }) => <p className="text-[17px] text-ink leading-[1.75] mt-3">{children}</p>

type Variant = { label: string; n: number; n_female: number; n_male: number; median_ratio: Record<string, number | null>; share_underfunded: Record<string, number | null>; female_shortfall_m: number; migraine_ratio: number | null }
function Sensitivity() {
  const [rows, setRows] = useState<Variant[]>([])
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/chapter3_sensitivity.json`).then(r => r.json()).then(setRows) }, [])
  if (!rows.length) return null
  return (
    <div className="mt-4 overflow-x-auto">
      <table className="w-full border-collapse text-[13px]">
        <thead><tr className="text-[11px] font-bold uppercase tracking-[0.12em] text-ink-3"><th className="py-2 pr-3 text-left font-bold">Variant</th><th className="py-2 pr-3 text-right font-bold">Diseases</th><th className="py-2 pr-3 text-right font-bold">Median ratio, women / men</th><th className="py-2 pr-3 text-right font-bold">Below line, women / men</th><th className="py-2 pr-3 text-right font-bold">Shortfall</th><th className="py-2 text-right font-bold">Migraine</th></tr></thead>
        <tbody>{rows.map(v => (
          <tr key={v.label} className="border-t border-hairline/60"><td className="py-2 pr-3 text-ink">{v.label}</td><td className="py-2 pr-3 text-right tabular-nums">{v.n}</td><td className="py-2 pr-3 text-right tabular-nums">{v.median_ratio.female?.toFixed(2)} / {v.median_ratio.male?.toFixed(2)}</td><td className="py-2 pr-3 text-right tabular-nums">{v.share_underfunded.female}% / {v.share_underfunded.male}%</td><td className="py-2 pr-3 text-right tabular-nums">${v.female_shortfall_m}M</td><td className="py-2 text-right tabular-nums">{v.migraine_ratio?.toFixed(2)}×</td></tr>
        ))}</tbody>
      </table>
    </div>
  )
}

export default function Methods() {
  return (
    <div className="mx-auto max-w-3xl px-4 pt-20 pb-16 prose-step fade-up">
      <header className="text-center pb-6">
        <p className="eyebrow">Methods</p>
        <h1 className="display mt-4 text-4xl sm:text-6xl font-light leading-[1.05]">How every number <span className="italic font-medium text-berry">was made</span>.</h1>
      </header>
      <P>Every chart on this site is generated from a public dataset by a script in our repository. This page explains what each chapter measures, how, and where it can mislead. If you find an error, open an issue; we will correct the page and note the change here.</P>

      <H>Chapter 1: Tested on men, prescribed to women</H>
      <h3 className="eyebrow mt-8">Trial enrollment by sex</h3>
      <P>The FDA publishes a Drug Trials Snapshot for each new molecular entity and original biologic it approves, beginning with 2015 approvals. We collected every snapshot page linked from the FDA's live index and from the Internet Archive's January 2023 capture of the index, which still lists the 2015–2022 pages the FDA has since removed from the live site. Each page states the number of male and female participants in the efficacy population, either in a sentence ("N (x%) male patients and N (y%) female patients") or in one or more baseline-demographics tables. Our parser reads the sentence where present; otherwise it reads the Female and Male rows of each baseline-demographics table, using the Total column where there is one and summing the arms where there is not. When the same trial is reported for two populations (safety and efficacy) the larger is used; distinct trials are summed. We publish only the female share; the participant count behind it is kept in the data file but can double-count overlapping populations on a few pages, so it is not shown on the charts. Where an archived page could not be retrieved from the Internet Archive or could not be parsed, we fall back to the figure in the independently compiled dataset of Carmeli and colleagues (2023), and flag that drug's enrollment source in the published data file. For the drugs both cover, we cross-checked our own parsed figures against theirs; the comparison is printed by the pipeline's check script.</P>
      <h3 className="eyebrow mt-8">Adverse-event reports by sex</h3>
      <P>We query the openFDA drug adverse event endpoint, which serves the FDA Adverse Event Reporting System (FAERS), for each drug by brand name, counting reports by patient sex. Reports with unknown sex are excluded from the denominator. Drugs with fewer than 100 sex-recorded reports are excluded from the scatter and the table because small counts make the share unstable. The query, counts, and retrieval date for every drug are stored in the repository.</P>
      <h3 className="eyebrow mt-8">The gap</h3>
      <P>For each drug we compute the female share of adverse-event reports minus the female share of pivotal-trial participants, in percentage points. We call a drug part of the "Ambien corner" when its trial was less than half women and the gap is 15 points or more. Both thresholds are choices; the chart's legend states them and the pipeline exposes them as parameters, so a reader who prefers 10 or 20 points can rerun it.</P>
      <h3 className="eyebrow mt-8">What the gap is not</h3>
      <P>It is not a harm rate. FAERS is a voluntary reporting system with no denominator: a drug taken mostly by women will generate mostly female reports whatever its safety profile. Women also report adverse events at higher rates than men across drugs. Reports can be duplicated, and openFDA links reports to drugs by name matching, which misses some. The gap identifies drugs where the post-market signal is tilted toward women relative to the evidence collected before approval. It is a prioritisation tool, not a finding of harm.</P>
      <h3 className="eyebrow mt-8">Reports per user</h3>
      <P>To adjust report shares for who takes each drug we use the Medical Expenditure Panel Survey (MEPS) Household Component, the federal survey of a national sample of households that records every prescription fill and the person's sex. We pool the Prescribed Medicines files for 2018 to 2024, join each fill to the person's sex in that year's Full Year Consolidated file, and count the persons with at least one fill of each drug, weighted with the person weight. Fills are matched to our drugs by the reported name, the same way the FAERS query was made: by brand name, or by generic name when every fill of that molecule in the survey is recorded under that brand or the generic name itself. A share is published only for drugs with at least 30 unweighted person-years of users.</P>
      <P>The ratio shown is the female-to-male ratio of adverse-event reports divided by the female-to-male ratio of users. It is reports per user, women relative to men. The 95% interval around each ratio comes from the binomial sampling error of the survey's share of users who are women, using the unweighted person-year count; the FAERS counts are large enough that their sampling error is ignored. It removes the largest confounder of the raw report share, but it is still built on voluntary reports and still cannot see dose, duration or severity. The survey is small for specialty drugs, so most biologics and cancer drugs have no ratio; that is a coverage limit, not evidence of anything.</P>
      <h3 className="eyebrow mt-8">Zolpidem figures</h3>
      <P>Dose changes, pharmacokinetic percentages and the 63% usage share come from the FDA's January 2013 Drug Safety Communication and its accompanying questions-and-answers page. Zolpidem's FAERS counts come from openFDA using the generic name.</P>
      <h3 className="eyebrow mt-8">Therapeutic area</h3>
      <P>The snapshots do not state a therapeutic area. We assign one with keyword rules applied to the FDA's own one-sentence description of what the drug is for. The rules are in the pipeline and the assignment is shown in every tooltip, so misclassifications are visible rather than hidden.</P>

      <H>Chapter 2: The urgency gap</H>
      <P>Data are the National Hospital Ambulatory Medical Care Survey (NHAMCS) emergency department public-use files for 2018 through 2022, from the National Center for Health Statistics. Each record is a sampled visit with the patient's sex and age, up to five reasons for visit, the triage pain score, waiting time to first contact with a physician, nurse practitioner or physician assistant, up to thirty medications with their therapeutic classes and whether each was given in the department or prescribed at discharge, triage level, arrival by ambulance, tests ordered, and disposition. We pooled the five years and kept visits by adults aged 18 and over.</P>
      <h3 className="eyebrow mt-8">Definitions</h3>
      <P>Pain complaints are defined by the first-listed reason for visit: abdominal pain (codes 1545.0–1545.3), chest pain (1050.0–1050.3), back pain (1905.0, 1905.1, 1910.0, 1910.1), headache or migraine (1210.0, 2365.0), neck, hip, leg or joint pain (1900.1, 1915.1, 1920.1, 1925.1, 1930.1, 1935.1) and flank, rib or groin pain (1055.0–1055.3). An opioid is any medication whose therapeutic class is narcotic analgesics (Multum 060) or narcotic analgesic combinations (191); any analgesic is Multum 058 through 063 or 191. "Given in the ED" uses the survey's given-or-prescribed item. Severe pain is a reported score of 7 to 10. Urgent triage is emergency severity index 1 or 2, and immediate is level 1. A heart attack visit is any visit with ICD-10 code I21 or I22 in any of the five diagnosis fields; its chief complaint is the first-listed reason for visit. Cardiac enzymes, D-dimer, EKG, imaging and CT are the survey's own test checkboxes. Arrival mode is the survey's arrival-by-ambulance item (walk-in means any other arrival). The explorer's age bands are 18–44, 45–64 and 65 and over; its cells with fewer than a few hundred sampled visits carry wide intervals, which are shown. Sex is the survey's SEX item, coded 1 for female and 2 for male; our first build of this chapter read it the other way round and was withdrawn the same day, and every figure here is from the corrected run.</P>
      <h3 className="eyebrow mt-8">Estimation</h3>
      <P>All shares and means are weighted with the visit weight and their standard errors come from Taylor linearization over the survey's masked strata and primary sampling units, following NCHS guidance for pooling years. Differences between women and men treat the two domains as independent. Age adjustment is direct standardization of each sex's rate to the pooled age distribution of that complaint in three bands (18–44, 45–64, 65+). Wait time excludes visits where it was not recorded; the pain-score analysis uses only the three-fifths of visits with a recorded score. We report means for wait time because the survey design does not give a clean standard error for the median; medians are in the data file.</P>
      <h3 className="eyebrow mt-8">Adjusted models</h3>
      <P>For each gap we fit a logistic regression of the outcome on patient sex with age band (18–44, 45–64, 65+), complaint group, survey year and, where stated, the reported pain score, arrival by ambulance and whether the chief complaint was chest pain. Visits are weighted by the visit weight normalised to a mean of one, and standard errors are clustered on stratum by primary sampling unit, which approximates the survey design. Odds ratios are for women relative to men. The full specifications and results are in the chapter's models file.</P>
      <h3 className="eyebrow mt-8">What it cannot see</h3>
      <P>The survey records what was documented, not dose, time from order to administration, or the clinician's reasoning. Sex is recorded as male or female. The 2008 comparison study measured time to analgesia in one department; the survey measures time to a clinician nationally, so the two are compared in direction, not in minutes.</P>

      <H>Chapter 3: The research dollar</H>
      <P>Funding is NIH's Estimates of Funding for Various Research, Condition, and Disease Categories (RCDC), pulled from the report.nih.gov API, in millions of dollars by fiscal year. Burden is the WHO Global Health Estimates: disability-adjusted life years (DALYs) by cause and sex for the United States, from the all-ages sheet of the country files for 2010, 2015, 2019, 2021 and 2023, with years lived with disability from the matching YLD file. The main analysis uses FY2024 funding against 2021 burden, the latest pairing available when the chapter was built.</P>
      <h3 className="eyebrow mt-8">Matching</h3>
      <P>Each NIH category was matched by hand to one or more WHO causes with the same definition. Most matches are one to one. Documented exceptions: hepatitis B and C include the cirrhosis and liver cancer WHO attributes to each virus; lymphoma pairs with Hodgkin plus non-Hodgkin; back and neck pain sums two NIH categories; five gynaecological NIH categories (endometriosis, fibroids, PCOS, vulvodynia, pelvic inflammatory disease) are summed against WHO's single gynaecological-diseases cause; vision loss sums five WHO causes. Diseases with fewer than 15,000 US DALYs are excluded because a dollars-per-DALY figure is unstable for them. Every match is listed in the chapter's data file.</P>
      <h3 className="eyebrow mt-8">Expected funding</h3>
      <P>Following the 2021 study, we fit a power law of funding on burden across all matched diseases (log funding = a + b log DALYs, ordinary least squares) and call the fitted value "expected" funding for that burden. A disease's ratio to expected is its actual funding divided by that. A disease is "mostly women" when at least 60% of its DALYs fall on women, "mostly men" at 60% or more on men. The shortfall is the sum, over mostly-women diseases below the line, of expected minus actual funding. The trend repeats the fit for each burden year with that fiscal year's funding.</P>
      <h3 className="eyebrow mt-8">Sensitivity</h3>
      <P>The table shows how the headline numbers move under other reasonable choices. The aggregate medians are fragile: dropping the two globally funded diseases, or moving the threshold, changes which sex's median sits higher. The disease-level findings are not: migraine's ratio stays between 0.14 and 0.16 in every variant, and the share of mostly-women diseases below the line stays at half or more.</P>
      <Sensitivity />
      <h3 className="eyebrow mt-8">What it cannot see</h3>
      <P>NIH categories overlap, so dollars are not additive across diseases, and some categories are broader than the WHO cause they are matched to. NIH funds some diseases for their global burden, which the US DALY figure does not capture; HIV and tuberculosis are the clearest cases and are shown rather than dropped. Conditions with no WHO cause cannot be placed on the chart; the chapter lists them separately with their funding.</P>

      <H>Chapter 4: Who gets studied</H>
      <P>Data are every interventional study on ClinicalTrials.gov with posted results, retrieved through the registry's version 2 API with a fixed list of fields: start date, phase, lead sponsor class, conditions with their MeSH terms and ancestor terms, eligibility criteria text and sex, minimum and maximum age, enrolment, site countries, baseline participant counts by sex, and the titles of the groups each outcome is reported for. The main analysis uses studies with at least one US site. The raw pages are cached and the parsed file is in the repository.</P>
      <h3 className="eyebrow mt-8">Women's share and the burden ratio</h3>
      <P>Each study's baseline "Sex" or "Gender" measure gives female and male participant counts; we take the total group where one exists and otherwise sum the arms. Where that sum exceeds the study's stated enrolment by more than a tenth, the baseline groups overlap (the same people counted in several periods or populations) and the study's sex counts are set aside; it still counts as a trial. A study is matched to a disease when any of its MeSH condition terms or ancestors is in that disease's list, which is printed in the pipeline; the diseases are those of Chapter 3, so each has a women's share of US DALYs from the WHO Global Health Estimates for 2021. The ratio is the women's share of all participants in the disease's trials (sex-restricted trials included) divided by the women's share of burden. A disease is shown when it has at least ten US trials. Sex-specific diseases have no ratio. The aggregate trend uses trials open to both sexes whose conditions are not sex-specific, by start year, with years holding fewer than thirty such trials dropped.</P>
      <h3 className="eyebrow mt-8">Exclusions and age limits</h3>
      <P>Eligibility text is searched case-insensitively with regular expressions, published in the pipeline: a pregnancy exclusion is any mention of pregnancy in the exclusion-criteria section, a pregnancy-test requirement, or the word pregnancy or pregnant near an excluding verb, except in trials whose conditions are themselves about pregnancy; lactation is lactating, breastfeeding or nursing mothers; contraception is contraception, birth control, barrier methods, an intrauterine device or abstinence; the "childbearing potential" clause is that phrase or its synonyms (reproductive potential, WOCBP, able to become pregnant). An upper age limit is any maximum age below 100 years. The counts are descriptive: they measure what the text says, which can differ from what sites enforced.</P>
      <h3 className="eyebrow mt-8">Age</h3>
      <P>Where a study reports the registry's standard age categories at baseline (under 18, 18 to 64, 65 and over), we take the count aged 65 and over in the total group, or the sum across arms. A disease's share of participants over 65 pools those studies. The share of burden after 65 is approximated from the WHO country file's age sheets as the 70-and-over band plus half of the 60-to-69 band; women's share of the 70-and-over burden is read directly. The age comparison is shown for diseases with at least half their burden after 65 and at least ten studies reporting age categories.</P>
      <h3 className="eyebrow mt-8">Results by sex</h3>
      <P>A trial "reports a result by sex" when at least one outcome measure is reported for a group named for females (female, women, girls) and a separate group named for males (male, men, boys), with no single group naming both. A women-only trial, or one with a "male and female" cohort, does not count. This catches sex-stratified reporting that the registry's structure can hold; a sex analysis mentioned only in free text is missed.</P>

      <H>Chapter 5: Sent home with a label</H>
      <P>Data are the same NHAMCS emergency department files as Chapter 2, adults 18 and over, restricted to visits the survey does not classify as injury-related and that carry a valid first-listed diagnosis. Twelve complaint groups are defined by the first-listed reason for visit: abdominal pain (1545.0–1545.3), chest pain (1050.0–1050.3), shortness of breath (1415.0), headache or migraine (1210.0, 2365.0), dizziness or vertigo (1225.0), weakness or fatigue (1020.0, 1020.1, 1015.0), fainting (1030.0), palpitations (1260.0), nausea or vomiting (1525.0, 1530.0), and the back, flank and limb pain groups of Chapter 2.</P>
      <h3 className="eyebrow mt-8">Definitions</h3>
      <P>A visit ends with a symptom code when its first-listed ICD-10-CM diagnosis is in chapter XVIII (R00–R99). "Nothing but symptom or encounter codes" means every listed diagnosis is in chapter R or Z. An anxiety or stress code is any diagnosis in F40–F48 (anxiety, stress-related and somatic symptom disorders) in any of the five diagnosis fields; "any psychiatric code" is any F code excluding organic (F00–F09) and substance-related (F10–F19) disorders. Named-diagnosis groups in the complaint tables are listed in the pipeline. A 72-hour return is the survey's item asking whether the patient was seen in the same department within the previous 72 hours, among visits where it was answered. Tests ordered is the survey's count of diagnostic services. Anxiety as a stated reason is reason-for-visit codes 1100.0 or 1105.0 in any of the three slots; "psychological symptom" is any reason code in 1100–1199.</P>
      <h3 className="eyebrow mt-8">Estimation and models</h3>
      <P>Shares are survey-weighted with Taylor-linearised standard errors over the masked design variables, as in Chapter 2, and age adjustment is direct standardisation to three bands. The adjusted models are survey-weighted logistic regressions of each outcome on patient sex with age band, complaint, year and, where stated, tests ordered, any imaging, triage level and arrival by ambulance, with errors clustered on stratum by sampling unit. The population comparison uses the NIMH's published past-year prevalence of any anxiety disorder, 23.4% of women and 14.3% of men, from the National Comorbidity Survey Replication.</P>
      <h3 className="eyebrow mt-8">Cancer stage and age at diagnosis</h3>
      <P>Stage and age come from the SEER*Explorer data archive for the November 2024 submission: the stage distribution of incident cases for 2013 to 2022 and the median age at diagnosis for 2018 to 2022, by sex, all races, from the 22 SEER registries. Stage is SEER summary stage. We keep the main sites that both sexes get, dropping histological subtypes, combined groupings and sex-specific sites, and sites with fewer than 2,000 cases in either sex. The distant-stage share is compared between women and men with a binomial interval on each share. The age-standardised comparison weights the sex-specific distant share within three age bands (under 50, 50 to 64, 65 and over) by the site's pooled age distribution. Median age is reported as published.</P>
      <h3 className="eyebrow mt-8">What it cannot see</h3>
      <P>The survey records the diagnoses written, not the reasoning, and cannot follow a patient to a later diagnosis elsewhere. The 72-hour return item does not say why the patient came back. A code's presence does not say whether it was the explanation offered to the patient. The chapter therefore tests what a single visit can test and says so.</P>

      <H>Chapter 6: The male default body</H>
      <h3 className="eyebrow mt-8">Rodent and human studies by sex</h3>
      <P>Counts come from PubMed's E-utilities search endpoint, one query per year, field and sex pattern. A rodent study is any record indexed with the Mice or Rats MeSH heading; its sex pattern is the Male and Female check tags: Male and not Female is male-only, Female and not Male is female-only, both tags is both. Shares are among records carrying at least one sex tag. Fields are defined by MeSH headings: neuroscience (neurosciences, brain, neurons, nervous system diseases), pain (pain, nociception, hyperalgesia, analgesics), cardiovascular (cardiovascular diseases or system), immunology (immune system diseases, immunity, inflammation), pharmacology (pharmacokinetics, preclinical drug evaluation, dose-response), metabolism and endocrine (metabolic and endocrine diseases, obesity, diabetes), behaviour and psychiatry (animal behaviour, mental disorders, psychological stress), reproduction and urogenital. NIH-funded papers are those with an NIH grant acknowledgement in the grant field. Human trials are records with the Clinical Trial or Randomized Controlled Trial publication type and the Humans heading, with the same check tags. The series end in 2020: the National Library of Medicine moved to automated MeSH indexing over 2021 and 2022, and the share of records carrying a sex tag halves at that point, so later years are not comparable and are kept only in the data file. Check tags are applied when the paper states the animals' sex; about half of rodent papers carry neither tag and are outside the shares shown.</P>
      <h3 className="eyebrow mt-8">Drug labels</h3>
      <P>For each Chapter 1 drug we retrieve the current label from the openFDA drug labeling endpoint by brand name (falling back to the generic name), keeping the prescription label with the latest effective date. The pharmacokinetics and clinical pharmacology sections are split into sentences, and sentences mentioning sex, gender, women, men, female or male are classified with regular expressions published in the pipeline: a quantified difference (a percentage or fold change tied to women or to sex), a difference noted without a number, an assertion of no clinically significant difference, a statement that sex was not evaluated, or silence. A label reports male-only pharmacokinetics when its pharmacology section describes a study in healthy male subjects or volunteers, or states the drug has not been studied in females. Pregnancy and lactation statements are classified as absent or insufficient when the specific-populations text says there are no, limited or insufficient human data. A sex-specific dose is detected from the dosage section. A label is weight-based when its dosage section doses by kilogram, by body surface area or explicitly by weight, and flat otherwise; the pharmacology section is classified as stating that exposure changes with body weight, stating that it does not, or silent, with the matched sentence kept. Mean adult body weight (men 90.3 kg, women 77.9 kg) is from the NCHS anthropometric reference data for August 2021 to August 2023, adults aged 20 and over. The share of trial reports analysing sex is the PubMed count of randomised controlled trial reports tagged both Male and Female that also carry the Sex Factors or Sex Characteristics heading, divided by all such reports, by year to 2020. Each drug's matched sentence is shown in the chapter's lookup so the classification can be checked.</P>

      <H>Reproducing the analysis</H>
      <P>Clone the repository, create a Python environment from <code>pipeline/requirements.txt</code>, and run the scripts in order: fetch snapshots, fetch FAERS counts, fetch MEPS users, build chapter 1; then build chapter 2 and chapter 5 from the NHAMCS files, chapter 3 from the NIH and WHO files, chapter 4 from the ClinicalTrials.gov pages (fetch trials), and chapter 6 from the PubMed counts and openFDA labels (fetch pubmed, fetch labels). All HTTP responses are cached, so a rerun is fast and offline. The site reads the resulting JSON files from <code>site/public/data</code>.</P>

      <H>Sources</H>
      <SourceList />
    </div>
  )
}
